name: Keep Alive
on:
  schedule:
    - cron: '*/40 * * * *'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s "https://huggingface.co/spaces/username/your-space-name" > /dev/null
